name: geolocation_sample
description: A Sample for debugging  flutter_background_geolocation issues 
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_background_geolocation: ^4.3.0
  pretty_json: ^2.0.0
  hive_flutter: ^1.1.0
  rxdart: ^0.27.2
  hive: ^2.0.4
  equatable: ^2.0.3
  shared_preferences: ^2.0.8
  flutter_cache_manager: ^3.1.2
  sensortracker:
    # When depending on this package from a real application you should use:
    #   sensortracker: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: sensortracker
  sensors_plus: ^1.1.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
